---
title: "Relay Host Dashboard"
subtitle: "Home"

header: false
footer: '<p><a href="https://github.com/cityplug?tab=repositories"><i class="fab fa-github-alt"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://redi1.soccerstreams.net/"><i class="fas fa-futbol"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://www3.gogoanime.cm/category/shingeki-no-kyojin-the-final-season-part-2"><i class="fas fa-dragon"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://anydesk.com/uk/downloads/thank-you?dv=win_exe"><i class="fas fa-download"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://dash.cloudflare.com/login/"><i class="fa-brands fa-cloudflare"></i></a></p>'
target: "_blank" # optional html a tag target attribute

stylesheet:
  - "assets/custom.css"

columns: "4" # Change this to any number: (1, 2, 3, 4, 6, 12)
colors:
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

  light:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#EAEAEA"
    text-header: "#7C71DD"
    text-title: "#C1C1C1"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#C1C1C1"
    link-hover: "#C1C1C1"
    background-image: "../assets/wallpaper.jpeg"

links:
 - name: "Google.co.uk"
   icon: "fa-brands fa-google"
   url: "https://www.google.co.uk/?gws_rd=ssl"
   target: "_blank" # optional html a tag target attribute
 - name: "Youtube"
   icon: "fa-brands fa-youtube"
   url: "https://www.youtube.com/"
   target: "_blank" # optional html a tag target attribute

services:
  - name: "//Hardware"
    icon: "fa-solid fa-server"
    items:
      - name: "Wireguard"
        logo: "assets/tools/wireguard.png"
        subtitle: "VPN Server"
        tag: "app"
        tagstyle: "is-link"
        url: "http://192.168.50.254:24792/"
        target: "_blank" # optional html a tag target attribute
      - name: "Shell"
        logo: "assets/tools/shell.png"
        subtitle: ""
        tag: "core"
        tagstyle: "is-link"
        url: "https://192.168.50.254:6105/"
        target: "_blank" # optional html a tag target attribute

  - name: "//Services"
    icon: "fa-solid fa-gears"
    items:
      - name: "Pihole"
        logo: "assets/tools/pihole.png"
        subtitle: "DNS"
        tag: "service"
        tagstyle: "is-success"
        url: "http://192.168.50.253/admin/"
        target: "_blank" # optional html a tag target attribute
      - name: "Unifi Remote"
        logo: "assets/tools/controller.png"
        subtitle: "Ubiquiti Remote"
        tag: "core"
        tagstyle: "is-link"
        url: "https://unifi.cityplug.co.uk:8443"
        target: "_blank" # optional html a tag target attribute
      - name: "Unifi Home"
        logo: "assets/tools/unifi.png"
        subtitle: "Ubiquiti Home"
        tag: "core"
        tagstyle: "is-link"
        url: "https://192.168.50.254:8443"
        target: "_blank" # optional html a tag target attribute

#  - name: "//Management"
#    icon: "fa-solid fa-folder-open"
#    items:
#      - name: "Files"
#        logo: "assets/tools/files.png"
#        subtitle: ""
#        tag: "link"
#        tagstyle: "is-link"
#        url: "http://192.168.50.254:8222"
#        target: "_blank" # optional html a tag target attribute

  - name: "//Estate"
    icon: "fa-solid fa-house-lock"
    items:
      - name: "Pluto"
        logo: "assets/tools/ghost.png"
        subtitle: ""
        tag: "bridge"
        tagstyle: "is-link"
        url: "#pluto"
#        target: "_blank" # optional html a tag target attribute
